name: Unit Test Check

on:
  pull_request:
    types: [ assigned, unassigned, labeled, unlabeled, opened, edited, reopened, synchronize ]
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          ./gradlew :com.example.presentation:test
